Algoritmo EJERCICIO_12
	DEFINIR NUM, CONT, NUM_NUEVO Como Entero;
	
	
	ESCRIBIR "DAME UN NUMERO";
	LEER NUM;

	CONT=NUM;
	NUM_NUEVO=1;

	MIENTRAS CONT>0 Hacer
		NUM_NUEVO=NUM_NUEVO*CONT;
		CONT=CONT-1;
	FinMientras
	ESCRIBIR NUM_NUEVO;
	
	
FinAlgoritmo